import React from "react";
import { Navbar, Footer } from "@components/index";
import Head from "next/head";
const Layout = ({ title, canonical, children }) => {
  const layoutBackground = "bg-white";
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`bg-white `}>
        <header>
          <Navbar />
        </header>
        <main>
          <div className="pt-32 sm:pt-16">{children}</div>
        </main>
        <Footer />
      </div>
    </div>
  );
};

export default Layout;
